# Generated by Django 4.1.2 on 2022-10-31 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='role',
            field=models.CharField(choices=[('Wicket Keeper', 'Wicket Keeper'), ('Batsman', 'Batsman'), ('Baller', 'Baller'), ('All Rounder', 'All Rounder')], default='Batsman', max_length=15),
        ),
        migrations.AlterField(
            model_name='player',
            name='grade',
            field=models.CharField(choices=[('12', 'XII'), ('11', 'XI'), ('10', 'X'), ('9', 'IX'), ('8', 'IIX')], default=('12', 'XII'), max_length=5),
        ),
    ]
