# Generated by Django 4.1.2 on 2022-10-31 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_player_role_alter_player_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='grade',
            field=models.IntegerField(default=12),
        ),
    ]
